### ISSUE TITLE
Error when using wordcloud from docker

### ISSUE THREAD

**Issue by fountainheadpro** [lightning-viz/lightning-wordcloud#1]
I launched lightning-viz vi a docker on mac. Then I did import visualization via github http link.
The import was successful, but I'm unable to run the visualization. I have this error in the log.
Error: Cannot find module './src' from '/usr/src/app/tmp/js-build/ca8f7ffd-52a5-4e94-bebf-4b8d4a860fee'
    at /usr/src/app/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/src/app/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/src/app/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/src/app/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)

Seem like some kind of path issue.

**Comment by mathisonian** [comment]
@fountainheadpro could you try with the updated docker build from https://hub.docker.com/r/lightningviz/lightning/ and let me know if there are still issues

**Comment by fountainheadpro** [comment]
Looks like I can import now. Thanks!
