### ISSUE TITLE
What's the best way to use the wordcloud from scala api?

### ISSUE THREAD

**Issue by fountainheadpro** [lightning-viz/lightning-wordcloud#2]

**Comment by mathisonian** [comment]
the scala client exposes a [plot method](https://github.com/lightning-viz/lightning-scala#using-a-custom-plot) that can be used like:

``` scala
val viz = lgn.plot("lightning-wordcloud", Map("words" -> List("data", "viz", "word", "cloud"), "counts" -> List(12, 3, 5, 9)))

val vizURL = viz.getPermalinkURL
```

to produce 
![screen shot 2015-12-06 at 12 37 47 am](https://cloud.githubusercontent.com/assets/1074773/11611897/9de5ccc6-9bb1-11e5-96b3-7c92b7389100.png)

**Comment by fountainheadpro** [comment]
Sweet, thanks!
